language: minimal
notifications:
  email:
    - tbekolay@gmail.com

env:
  global:
    - PYTHON="3.7"
    - PYTEST="pytest"
    - MODE="test"

matrix:
  include:
    - env: PYTHON="2.7"
    - env: PYTHON="3.4" PYTEST="pytest<4"
    - env: PYTHON="3.5"
    - env: PYTHON="3.6"
    - env: PYTHON="3.7"
    - env: MODE="static"
    - env: MODE="docs"

before_install:
  - source .ci/conda.sh install

install:
  - .ci/$MODE.sh install

script:
  - .ci/$MODE.sh script

after_success:
  - .ci/$MODE.sh after_success

after_script:
  - .ci/$MODE.sh after_script
