name: CI testing
on:
  pull_request: {}
  push:
    branches:
      - main
      - release-candidate-*
    tags:
      - v*
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Run the build with SSH debugging enabled
        type: boolean
        required: false
        default: false

jobs:
  test:
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - script: static
          - script: test
            coverage-name: oldest
            python-version: "3.7"
          - script: test
            coverage-name: newest
          - script: test
            os: windows-latest
          - script: docs
      fail-fast: false
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    env:
      COV_CORE_SOURCE: pytest_plt
      COV_CORE_CONFIG: setup.cfg
      COV_CORE_DATAFILE: .coverage.eager
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: nengo/nengo-bones/actions/setup@main
        with:
          python-version: ${{ matrix.python-version || '3.9' }}
      - uses: nengo/nengo-bones/actions/generate-and-check@main
      - uses: nengo/nengo-bones/actions/run-script@main
        with:
          name: ${{ matrix.script }}
      - uses: actions/upload-artifact@v3
        if: ${{ always() && matrix.coverage-name }}
        with:
          name: coverage-${{ matrix.coverage-name }}
          path: .coverage
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - test
    if: ${{ always() }}
    steps:
      - uses: nengo/nengo-bones/actions/coverage-report@main
  deploy:
    needs:
      - test
    if: >-
      startsWith(github.ref_name, 'release-candidate-') ||
      (github.ref_type == 'tag' && startsWith(github.ref_name, 'v'))
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Write .pypirc to file
        run: |
          echo '${{ secrets.PYPIRC_FILE }}' > ~/.pypirc
      - uses: actions/checkout@v3
      - uses: nengo/nengo-bones/actions/setup@main
      - uses: nengo/nengo-bones/actions/generate-and-check@main
      - uses: nengo/nengo-bones/actions/run-script@main
        with:
          name: deploy
